Download binary from REPO instead of building
hyphacoop/cosmos-ansible pull request #138
Opened 2022-07-20 19:49 UTC by YurkoWasHere

New variables added:

### gaiad_binary_source
**values:**
`build` (default) will compile a gaiad binary as it did before
`release` will download the gaiad binary from the git repo based on `gaiad_version` and `gaiad_binary_release`

### gaiad_binary_release
url to release binary. Uses `gaiad_version` to target bin
**value:** string
*note**: amd64 only

2022-07-21 20:02 UTC, dasanchez requested changes
Tested with `examples/inventory-local.yml`:
✅ without modifications
✅ `use_cosmovisor: false`
✅ `gaiad_binary_source: release`
✅ `use_cosmovisor: false` and `gaiad_binary_source: release`
Thanks @YurkoWasHere !

2022-07-22 02:50 UTC, YurkoWasHere commented on roles/gaia/tasks/main.yml
> +## Creatre go bin directory
```suggestion
## Create go bin directory
```

2022-07-22 02:51 UTC, YurkoWasHere commented on roles/gaia/tasks/main.yml
> +- name: Prepare cosmovisor folder
```suggestion
- name: Prepare go folder
```

2022-07-22 02:52 UTC, YurkoWasHere commented on roles/gaia/tasks/main.yml
> +    path: '{{ gaiad_user_home }}/go/bin'
Thanks, 
Copy paste fail

2022-07-22 12:40 UTC, dasanchez approved these changes

2022-07-22 12:41 UTC, merged