add auto joining parameters
hyphacoop/cosmos-ansible pull request #144
Opened 2022-07-21 05:08 UTC by ASoTNetworks

2022-07-21 12:08 UTC, YurkoWasHere commented on examples/inventory-mainnet.yml
> +    chain_info_server: "https://rpc.cosmos.network:443"
Is this gaiad specific or do all chains have a rpc server like this?

2022-07-24 02:46 UTC, dasanchez requested changes
This is so good, great job @ASoTNetworks!
I have one request- could you change all the file names and workflows from "mainnet" to "cosmoshub"?
- `test-mainnet-node.yml` -> `test-cosmoshub-node`
- `inventory-mainnet.yml` -> `inventory-cosmos-hub.yml`

2022-07-24 02:46 UTC, dasanchez commented on README.md
> +[![Join Cosmos Mainnet](https://github.com/hyphacoop/cosmos-ansible/actions/workflows/test-mainnet-node.yml/badge.svg?branch=main)](https://github.com/hyphacoop/cosmos-ansible/actions/workflows/test-
This is amazing!
Same thing, "Join Cosmos Hub"

2022-07-24 02:46 UTC, dasanchez commented on docs/Playbook-Variables.md
> +| `chain_registry` | When set it will automatically define `gaiad_version`, `chain_id` and `genesis_url` variables from the chain registry file | `https://registry.ping.pub/testnets/theta/chain.json`
Very nice

2022-07-24 02:46 UTC, dasanchez commented on .github/workflows/test-mainnet-node.yml
> +  test-theta-testnet:
test-join-cosmoshub

2022-07-24 02:46 UTC, dasanchez commented on .github/workflows/test-mainnet-node.yml
> +name: Join Cosmos Mainnet
Join Cosmos Hub

2022-07-26 13:30 UTC, merged