Split up gaia main.yml
hyphacoop/cosmos-ansible pull request #147
Opened 2022-07-22 15:51 UTC by makeworld-the-better-one

Fixes #120 

I've tested this with `inventory-local.yml`, and after that completed successfully I tested the faucet by hand to make sure it could read balances. Let me know if other testing is needed.

Steps were copied into new files, but no meaningful modifications were made. At most the order of some of the steps was changed to align with the topic of each new file.

2022-07-22 19:44 UTC, dasanchez requested changes
This is great, thanks @makeworld-the-better-one 
Could you split up the `apis.yml` further and move the node exporter/prometheus/panic tasks into a `monitoring.yml` file?

2022-07-22 21:25 UTC, makeworld-the-better-one commented
@dasanchez done.

2022-07-23 01:59 UTC, dasanchez approved these changes

2022-07-23 02:59 UTC, YurkoWasHere approved these changes
Awsome job, this make the code much more readable as major tasks are now grouped together.

2022-07-26 19:45 UTC, merged