Chain agnostic role: node
hyphacoop/cosmos-ansible pull request #159
Opened 2022-07-28 17:41 UTC by makeworld-the-better-one

Fixes #129

Changing vars programmatically with: `fd -H --ignore-vcs -E '.git' -t f | xargs sed -i 's/gaiad_home/chain_home/g'`

Each var change is its own commit to allow for easy diffing and spotting of mistakes.

These changes will be moved to their own role (and gaia will be untouched) before merging. For now the gaia roles is modified to allow for better diffs for review.

2022-07-30 01:20 UTC, dasanchez reviewed
This is excellent, great progress so far!
I added five more variables to the table:
- `gaiad_api_host` -> `chain_api_host`
- `gaiad_rpc_host` -> `chain_rpc_host`
- `gaiad_p2p_host` -> `chain_p2p_host`
- `gaiad_grpc_host` -> `chain_grpc_host`
- `gaiad_use_ssl_proxy` -> `chain_use_ssl_proxy`

There are two items that can come after the move to the `node` role, or they could even get a separate issue afterwards:
- `examples/README.md`
- `gaia_control.py` and the `gaiad_` tags it has peppered throughout the role

Good idea leaving everything in the `gaia` role for reviewing- I'm OK if you want to move things over to the `node` role now.

2022-07-30 01:20 UTC, dasanchez commented on docs/Playbook-Variables.md
> -| `gaiad_home`           | Path to Gaia home folder home                                                   | `/home/gaia/.gaia`                                                                 |
Path to chain home folder
(the "home folder home" typo is definitely mine)

2022-08-02 13:28 UTC, makeworld-the-better-one commented
> There are two items that can come after the move to the `node` role, or they could even get a separate issue afterwards:
> - `examples/README.md`
> - `gaia_control.py` and the `gaiad_` tags it has peppered throughout the role

I think the README should be a separate issue that tackles documentation of this chain agnostic setup as a whole, across all the documentation. I will update `gaia_control.py` in this PR though.

2022-08-03 13:07 UTC, dasanchez reviewed
This is great @makeworld-the-better-one 
The next step will be to replace _most_ instances of `gaiad` with a `chain_binary` or `chain_binary_name` variable, but I think this is a solid starting place.

2022-08-03 13:07 UTC, dasanchez commented on roles/node/tasks/apis.yml
> +- name: Setup nginx SSL for gaiad api endpoint
Remove gaiad

2022-08-03 13:07 UTC, dasanchez commented on roles/node/tasks/apis.yml
> +- name: Setup nginx SSL for gaiad rpc endpoint
Remove gaiad

2022-08-03 13:07 UTC, dasanchez commented on roles/node/tasks/apis.yml
> +- name: Setup nginx SSL for gaiad GRPC endpoint
Remove gaiad

2022-08-03 13:07 UTC, dasanchez commented on roles/node/tasks/apis.yml
> +- name: Setup nginx SSL for gaiad P2P endpoint
Remove gaiad

2022-08-08 13:10 UTC, dasanchez commented on node_control.py
> +    print(os.popen("ansible-playbook node.yml -i " +
This command is missing a `target` argument.

2022-08-08 13:12 UTC, dasanchez requested changes
The `node_control.py` needs a `target` flag in the restart operation.

2022-08-08 13:45 UTC, makeworld-the-better-one commented
Good catch thanks. Fixed.

2022-08-08 14:22 UTC, dasanchez approved these changes
Looks good!

2022-08-08 14:33 UTC, dasanchez commented
Tested:
- Local testnet (including faucet)
  - v6.0.4
  - v7.0.0
- Theta testnet
- node_control.py: start, stop, restart, reset
- Gaia upgrade via governance:
  - v6.0.4 -> v7.0.0
  - v6.0.4 -> v7.0.3

2022-08-08 14:35 UTC, merged